name: v2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  mongo_dart: ^0.8.0
  http:
  intl:
  dio:
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  shared_preferences:
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/vectors/Images/
